


export default function generateAutoDraftMap () {
    const autoDraftMap = new Map<string, string>();
    computerTeamNames.forEach((teamName, index) => {
        autoDraftMap.set(`autodraft-${index}`, teamName);
    });
    return autoDraftMap;
}

const computerTeamNames = [
    "Plattsburgh Pixel Pirates",
    "Saltaire Superusers",
    "Allentown Algorithms",
    "Centerport Circuit Breakers",
    "Greene Grid Guardians",
    "Seneca Falls Syntax",
    "Milan Motherboards",
    "Riverside RAM Raiders",
    "East Rockaway Encryption",
    "Montour Falls Modems",
    "Wurtsboro Widgets",
    "Dayton Debuggers",
    "Plymouth Processors",
    "Franklin Square-Munson Firewalls",
    "Rhinecliff Renderers",
    "Constable Coders",
    "Schuyler Script Runners",
    "Strykersville SysOps",
    "West Valley Volt Vipers",
    "Lakeland Logic",
    "Deposit Data Dogs",
    "Randolph Runtimes",
    "Trout Creek Tech Titans",
    "Brier Hill Bit Bandits",
    "Jericho Java Jacks",
    "Berne Binary Beasts",
    "West Monroe Web Warriors",
    "Liverpool Logic Lords",
    "West Stockholm Stack Snakes",
    "Mannsville Macro Machines",
    "New Hyde Park Network Ninjas",
    "Sunset Bay Server Squad",
    "Moira Microchip Marauders",
    "Preble Packet Pushers",
    "Chappaqua Cache Crew",
    "Camillus Code Crushers",
    "Darien Center Data Drivers",
    "Centerville Cyber Squad",
    "Croghan Cloud Chasers",
    "Bayville Byte Bruisers",
    "Mamaroneck Machine Minds",
    "Kendall Kernel Kings",
    "Troy Trojan Horses",
    "Rotterdam Pine Grove Registers",
    "Colden Crypto Collective",
    "Unionville Upload Union",
    "East Jewett Java Jets",
    "Minetto Motherboard Mob",
    "Piermont Ping Patrol",
    "Groveland GPU Gunners",
    "Fairville Firmware Force",
    "Roscoe/Rockland Runtime Rangers",
    "Otisville Overclockers",
    "Stephentown Silicon Storm",
    "Glens Falls Gigahertz",
    "Sammonsville Static Stack",
    "Otisco OS Operators",
    "Orangeburg Assn Overflow",
    "Lawrence-Cedarhurst Logic Lines",
    "Speculator Silicon Sparks",
    "Martinsburg Mod Creators",
    "Egypt Ethernet Engines",
    "Oriskany Omegabytes",
    "Somers Systematics",
    "East Syracuse Echo Servers",
    "Waterville Web Watchers",
    "Delanson Data Deacons",
    "Stuyvesant Streamers",
    "Best Luther Byte Battalion",
    "Middle Falls Mainframe",
    "Elma Emulator Express",
    "Taunton Thread Thrashers",
    "Cranesville Cache Crashers",
    "Port Chester Program Panthers",
    "Mountaindale Machine Code",
    "Gansevoort Glitch Gang",
    "Champion Chip Champions",
    "Benton Bit Brigade",
    "Kenmore Keyframe Knights",
    "Westville Waveform Warriors",
    "Grafton Graphics Guild",
    "Perry Pixel Pushers",
    "Lancaster LAN Legion",
    "Sodus Point Source Soldiers",
    "Dobbs Ferry Data Drivers",
    "Otego Output Operators",
    "Louisville Liquid Logic",
    "Stewart Manor Stack Masters",
    "Conquest Console Crew",
    "Wyandanch Web Walkers",
    "Tri-Village Terabyte Tribe",
    "Voorheesville Virtual Vipers",
    "West Crescent Code Command",
    "King Ferry Kernel Force",
    "Bennington Binary Battalion",
    "Morrisonville Macro Makers",
    "Enfield Encryption Eagles",
    "Angelica Analog Angels",
    "South Wilson Socket Soldiers"
  ];
  
export { computerTeamNames, generateAutoDraftMap };
  