import { faZ } from "@fortawesome/free-solid-svg-icons";

const imgLU: {[index:string]: string}  = {
    "Albertson Slo Pokes": "albertson.png", 
    "Baldwin Tomcats": "baldwin.png", 
    "Bay Shore Redskins": "Bay Shore.PNG", 
    "Bay Shore Jr. Redskins": "Bay Shore.PNG", 
    "Bellmore Ballbreakers": "bellmore.png", 
    "Carle Place Frogs": "Carle Place.PNG", 
    "Carle Place Jr. Frogs": "Carle Place.PNG", 
    "Central Islip Jr. Hoboes": "Central Islip.PNG", 
    "Central Islip Hoboes": "Central Islip.PNG", 
    "Copiague Yellowbirds": "Copiague.png", 
    "Deer Park Bucks": "Deer Park.PNG", 
    "East Farmingdale Hares": "east farm.png", 
    "East Farmingdale Jr. Hares": "east farm.png", 
    "East Islip Guzzlers": "East Islip.PNG", 
    "East Islip Jr. Guzzlers": "East Islip.PNG", 
    "Elsmere Wanderers": "Elsmere.png", 
    "Farmingville Bandits": "Farmingville.png", 
    "Farmingville Jr. Bandits": "Farmingville.png", 
    "Freeport Red Devils": "freeport.png", 
    "Great Bend Cobras": "Great Bend.png", 
    "Hagerman Gamblers": "Hagerman.png", 
    "Hagerman Jr. Gamblers": "Hagerman.png", 
    "Hempstead Yellow Hornets": "Hempstead.png", 
    "Henrietta Ol` Henries": "Henrietta.png", 
    "Hicksville Hicks": "Hicksville.png", 
    "Hicksville Jr. Hicks": "Hicksville.png", 
    "Islip Jr. Wolves": "Islip.png", 
    "Islip Wolves": "Islip.png", 
    "Levittown Rebels": "Levittown.png",
    "Lindenhurst Jr. Snails": "Lindenhurst.png", 
    "Lindenhurst Snails": "Lindenhurst.png", 
    "Manhasset-Lakeville Minute Men": "MinuteMen.png",
    "Main-Transit Slo-Pokes": "Main Transit.png", 
    "Miller Place Extinguishers": "Miller Place.png", 
    "New Hyde Park Termites": "New Hyde Park.png", 
    "North Babylon Tail Draggers": "North Babylon.png", 
    "North Babylon Jr. Tail Draggers": "North Babylon.png", 
    "North Bellmore Rinky Dinks": "North Bellmore.png", 
    "North Lindenhurst Piston Knockers": "North Lindenhurst.png", 
    "North Merrick Stump Jumpers": "North Merrick.png", 
    "Oyster Bay Teddy`s Boys": "Oyster Bay.png", 
    "Patchogue Forty Thieves": "Patchogue.png", 
    "Patchogue Jr. Forty Thieves": "Patchogue.png", 
    "Point Pleasant Pea Pickers": "Point Pleasant.png", 
    "Port Washington Road Runners": "Port Washington.png", 
    "Port Washington Jr. Road Runners": "Port Washington.png", 
    "Riverhead Ironmen": "riverhead.png", 
    "Riverhead Jr. Ironmen": "riverhead.png", 
    "Roslyn Highlanders": "Roslyn.png", 
    "Sea Breeze Indians": "Sea Breeze.png", 
    "Seaford Inmates": "Inmates.png",
    "Selden Slowpokes": "Selden.png", 
    "Selden Jr. Slow Pokes": "Selden.png", 
    "South Hempstead Rascals": "LittleRascal.png", 
    "Spencerport Red Onions": "SPENCERPORT.png", 
    "West Hempstead Westerners": "West Hempstead.png", 
    "West Islip Raiders": "West Islip.png", 
    "West Islip Jr. Raiders": "West Islip.png", 
    "West Sayville Flying Dutchmen": "West Sayville.png", 
    "West Sayville Jr. Flying Dutchmen": "West Sayville.png", 
    "Westbury Turtles": "Westbury.png", 
    "Westbury Jr. Turtles": "Westbury.png"
}

export default function getImgLocation(teamName:string):string | null{
    return imgLU[teamName] ? `/static/img/logos/${imgLU[teamName]}` : `/static/img/logos/NYSFDDT patch medium.png`; 
}